### ISSUE TITLE
Can't get project-specific syntax to work in ST3

### ISSUE THREAD

**Issue by cscomfort** [reywood/sublime-project-specific-syntax#10]
Hi reywood,

I've used this package in the past with success, but on a new install (**ST3 Build 3114**) I can't seem to get it to trigger the preferred syntax as defined in the sublime-project settings. Initially, I was trying to set the HTML syntax to use Jinja2 (via "Copy syntax setting to clipboard"), but I can't seem to get even built-in syntaxes to work when testing.

For example, neither of these work:

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "syntax_override": {
        "\\.html$": ["Jinja2", "Syntaxes", "HTML (Jinja2)"]
    }
}
```

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "syntax_override": {
        "\\.html$": ["Text", "Plain text"]
    }
}
```

Any thoughts as to what may going on?

Many thanks.

**Comment by dw-io** [comment]
Documentation on projects is pretty fuzzy.  I thought simply creating a `.sublime-project` file would work every time I opened that directory.  It does not.  You have to go to projects and save to a projects file.  Then, to get the rules to execute, you have to open that project file rather than just `subl .`

After figuring that out, things seem to work as expected.  All this time I never really used projects.

**Comment by reywood** [comment]
I have updated the README to hopefully be more clear and added links to information about projects and the project file format. Hope that helps.
